var URLS = {

	GET_FEATURED_CARS : "http://inceptumapps.com/carsstore/mobile/android/get_featured_cars.php",
	GET_FEATURED_CARS_LIMIT : "http://inceptumapps.com/carsstore/mobile/android/get_featured_cars_limit.php",
	GET_MAGAZINE : "http://elchebbi-ahmed.alwaysdata.net/xml_to_jsonMagasine.php",
	GET_CONCESSIONNAIRE : "http://inceptumapps.com/carsstore/mobile/android/get_concessionnaire.php",
	GET_BRANDS : "http://inceptumapps.com/carsstore/mobile/android/get_brands.php",
	GET_MODEL_BY_BRAND : "http://inceptumapps.com/carsstore/mobile/android/get_models_by_brand.php?brand_id=",
	GET_MODEL_RATING : "http://inceptumapps.com/carsstore/mobile/android/get_model_rating.php",
	GET_PHOTO_BY_MODEL : "http://inceptumapps.com/carsstore/mobile/android/get_photo_by_model.php?model_id=",
	GET_BRAND_LOGO : "",
	GET_GAMME_BY_MODEL : "http://inceptumapps.com/carsstore/mobile/android/get_gamme_by_model.php?model_id=",
	GET_PHOTO_BY_GAMME : "http://inceptumapps.com/carsstore/mobile/android/get_photo_by_gamme.php?gamme_id=",
	GET_GAMME_CARACTERISTIQUE : "http://inceptumapps.com/carsstore/mobile/android/get_gamme_caracteristique.php?caracteristique_id=",
	GET_GAMME_MOTORISATION : "http://inceptumapps.com/carsstore/mobile/android/get_gamme_motorisation.php?motorisation_id=",
	GET_USER_FAVORIS : "http://www.inceptumapps.com/carsstore/mobile/ios/get_user_favoris.php?user_id=",
	INSERT_INTO_FAVORIS : "http://www.inceptumapps.com/carsstore/mobile/ios/insert_into_favoris.php",
	DELETE_USER_FAVORIS : "http://www.inceptumapps.com/carsstore/mobile/ios/delete_user_favoris.php",
	GET_BODY_CARS : "http://inceptumapps.com/carsstore/mobile/android/get_body_cars.php",
	FILTER : "http://inceptumapps.com/carsstore/mobile/android/filter.php?",
	GET_GAMME_BY_ID : "http://inceptumapps.com/carsstore/mobile/android/get_gamme_by_id.php?gamme_id=",
	GET_BRAND_BY_ID : "http://inceptumapps.com/carsstore/mobile/android/get_brand_by_id.php?brand_id=",
	ADD_USER_ANNONCE : "https://www.inceptumapps.com/carsstore/mobile/tizen/insert_user_annonce_tizen.php",
	GET_MAKE_YEARS : "https://www.inceptumapps.com/carsstore/mobile/shared/get_makes_by_year.php?make_year=",
	GET_YEARS : "https://www.inceptumapps.com/carsstore/mobile/shared/get_make_years.php",
	GET_MODEL_BY_YEAR_AND_BRAND : "https://www.inceptumapps.com/carsstore/mobile/shared/get_models_by_make_and_make_years.php",
	GET_LAST_USER_ANNONCE_ID :"http://inceptumapps.com/carsstore/mobile/tizen/get_last_user_annonce_id_tizen.php?user_id=",
	INSERT_USER_ANNONCE_PHOTO_TIZEN : "http://inceptumapps.com/carsstore/mobile/tizen/insert_user_annonce_photo_tizen.php?",
	GET_MODEL_RATING : "http://inceptumapps.com/carsstore/mobile/tizen/get_model_rating_tizen.php?model_id=",
	GET_ANNONCE_BY_USER:"http://inceptumapps.com/carsstore/mobile/tizen/get_mes_annonce_tizen.php?user_id=",
	GET_ANNONCES_PHOTOS :"http://inceptumapps.com/carsstore/mobile/tizen/get_user_annonce_photos_tizen.php",
	GET_ALL_ANNONCES : "http://inceptumapps.com/carsstore/mobile/tizen/get_user_annonce_tizen.php",
	GET_ANNONCE_PHOTOS_BY_ANNONCE_ID :"http://inceptumapps.com/carsstore/mobile/tizen/get_user_annonce_photo_tizen_by_user.php?annonce_id=",
	
	
};
